/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import classes.Configuracao;
import excecoes.DinheiroInvalidoException;
import excecoes.QuantidadeInvalidaException;
import excecoes.ValidacaoException;
import janelaprincipal.JanelaPrincipal;
import java.awt.GridLayout;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;
import operacoes.AchaMaior;
import operacoes.CarregaModel;
import operacoes.SalvarJListLinked;
import validacoes.Validacoes;

/**
 *
 * @author Vini_
 */
public class JanelaConfiguracao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConfiguracao
     */
    private JanelaPrincipal janelaPrincipal;
    private DefaultListModel<String> model = new DefaultListModel<>();
    private MaskFormatter mascaraValor;

    public DefaultListModel getModel() {
        return model;
    }

    public void setModel(DefaultListModel model) {
        this.model = model;
    }

    public JanelaConfiguracao(JanelaPrincipal janelaPrincipal) {
        initComponents();
        if (!janelaPrincipal.getHashMap().getMapVagasReservadas().isEmpty()) {
            this.tValor.setEnabled(false);
            this.bAdicionar.setEnabled(false);
            this.bRemover.setEnabled(false);
        }
        try {
            this.mascaraValor = new MaskFormatter("#.##");
        } catch (ParseException ex) {
            Logger.getLogger(JanelaConfiguracao.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.janelaPrincipal = janelaPrincipal;
        CarregaModel.CarregaModel(janelaPrincipal.getConfiguracao().getVagas(), this);
        this.setLocationRelativeTo(janelaPrincipal);
        listVagas.setModel(model);
        this.tValor.setText("" + janelaPrincipal.getConfiguracao().getValor());
        this.tTolerancia.setText("" + janelaPrincipal.getConfiguracao().getTolerancia());
        this.setVisible(true);
    }

    public JList<String> getListVagas() {
        return listVagas;
    }

    public void setListVagas(JList<String> listVagas) {
        this.listVagas = listVagas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tTolerancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tValor = new javax.swing.JFormattedTextField(mascaraValor);
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVagas = new javax.swing.JList<>();
        bAdicionar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        bOK = new javax.swing.JButton();
        bCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cobrança", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Valor por Hora:");

        jLabel2.setText("Tolerância:");

        tTolerancia.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tTolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tToleranciaActionPerformed(evt);
            }
        });

        jLabel3.setText("R$");

        jLabel4.setText("Min");

        tValor.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tValor)
                    .addComponent(tTolerancia, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disposição do Estacionamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        listVagas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listVagas);

        bAdicionar.setText("Adicionar");
        bAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarActionPerformed(evt);
            }
        });

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRemover, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bAdicionar)
                .addGap(18, 18, 18)
                .addComponent(bRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        bCancela.setText("Cancelar");
        bCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(bOK)
                .addGap(27, 27, 27)
                .addComponent(bCancela)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOK)
                    .addComponent(bCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tToleranciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tToleranciaActionPerformed

    private void bAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarActionPerformed
        // TODO add your handling code here:
        new JanelaQuantidade(this);
        this.setEnabled(false);
    }//GEN-LAST:event_bAdicionarActionPerformed

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        // TODO add your handling code here:

        try {
            String strTolerancia = tTolerancia.getText();
            Validacoes.QUANTIDADE.valida(strTolerancia);
            int tolerancia = Integer.parseInt(strTolerancia);
            String strValor = tValor.getText();
            Validacoes.MONETARIO.valida(strValor);
            double valor = Double.parseDouble(strValor);
            if (!janelaPrincipal.getHashMap().getMapVagasReservadas().isEmpty()) {
                if (!model.isEmpty()) {
                    LinkedList<Integer> vagas = SalvarJListLinked.SalvarJListLinked(listVagas);
                    Configuracao configuracao = new Configuracao(valor, tolerancia, vagas);
                    janelaPrincipal.setConfiguracao(configuracao);
                } 
            }else{
                    if (!model.isEmpty()) {
                    LinkedList<Integer> vagas = SalvarJListLinked.SalvarJListLinked(listVagas);

                    Configuracao configuracao = new Configuracao(valor, tolerancia, vagas);
                    janelaPrincipal.setConfiguracao(configuracao);
                    JPanel painel = new JPanel();
                    painel = janelaPrincipal.getpVagas();
                    painel.setLayout(new GridLayout(AchaMaior.AchaMaior(configuracao), configuracao.getVagas().size(), 1, 1));
                    painel.removeAll();

                    janelaPrincipal.setpVagas(painel);
                    janelaPrincipal.criaBotao();

                }
            }
            janelaPrincipal.setEnabled(true);
            this.dispose();
        } catch (DinheiroInvalidoException | QuantidadeInvalidaException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (ValidacaoException ex) {
            Logger.getLogger(JanelaConfiguracao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bOKActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        // TODO add your handling code here:
        if (listVagas.getSelectedIndex() > -1) {
            model.remove(listVagas.getSelectedIndex());
            listVagas.setModel(model);
        }
    }//GEN-LAST:event_bRemoverActionPerformed

    private void bCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelaActionPerformed
        // TODO add your handling code here:
        janelaPrincipal.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_bCancelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public JFormattedTextField gettValor() {
        return tValor;
    }

    public void settValor(JFormattedTextField tValor) {
        this.tValor = tValor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionar;
    private javax.swing.JButton bCancela;
    private javax.swing.JButton bOK;
    private javax.swing.JButton bRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listVagas;
    private javax.swing.JTextField tTolerancia;
    private javax.swing.JFormattedTextField tValor;
    // End of variables declaration//GEN-END:variables
}
